import { db, spotsTable, bookingsTable, reviewsTable, payoutsTable, waitlistTable, surgeEventsTable } from "@workspace/db";
import { sql } from "drizzle-orm";

async function seed() {
  console.log("🌱 Seeding ParkEase Nairobi database...");

  console.log("  Clearing existing data...");
  await db.execute(sql`TRUNCATE TABLE reviews, payouts, bookings, surge_events, waitlist, spots RESTART IDENTITY CASCADE`);

  console.log("  Inserting 35 spots...");
  const insertedSpots = await db.insert(spotsTable).values([
    // ─── WESTLANDS ──────────────────────────────────────────────
    { ownerId: 4, title: "Westlands Square Driveway", description: "Secure private driveway in the heart of Westlands, 5 min walk to Sarit Centre.", address: "Westlands Rd, Westlands", zone: "Westlands", lat: -1.2672, lng: 36.8102, pricePerHour: 200, availableFrom: 7, availableTo: 21, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat"], hasCctv: true, hasRoofing: false, hasGate: true, spotType: "driveway", accessInstructions: "Green gate, code is 4521. Press buzzer if gate doesn't open.", photos: ["https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=600"], rating: 4.7, reviewCount: 12, totalBookings: 18, isActive: true },
    { ownerId: 3, title: "Sarit Centre Overflow Lot", description: "Open compound lot 100m from Sarit Centre. Easy in and out.", address: "Karuna Rd, Westlands", zone: "Westlands", lat: -1.2680, lng: 36.8090, pricePerHour: 150, availableFrom: 6, availableTo: 22, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"], hasCctv: false, hasRoofing: false, hasGate: false, spotType: "open_plot", accessInstructions: "Park anywhere in the open lot. No gate.", photos: ["https://images.unsplash.com/photo-1573946680645-e4ec9cf76082?w=600"], rating: 4.2, reviewCount: 8, totalBookings: 14, isActive: true },
    { ownerId: 5, title: "Westlands Office Basement B2", description: "Shaded basement spot in professional office block. Very secure.", address: "Waiyaki Way, Westlands", zone: "Westlands", lat: -1.2660, lng: 36.8115, pricePerHour: 300, availableFrom: 7, availableTo: 18, availableDays: ["Mon","Tue","Wed","Thu","Fri"], hasCctv: true, hasRoofing: true, hasGate: true, spotType: "basement", accessInstructions: "Enter from Waiyaki Way side. Basement level B2, spot 14. Security desk will give access card.", photos: ["https://images.unsplash.com/photo-1563694983011-6f4d90358083?w=600"], rating: 4.9, reviewCount: 21, totalBookings: 35, isActive: true },
    { ownerId: 6, title: "Ring Road Compound Slot", description: "Private compound with watchman on duty. Spacious for any vehicle.", address: "Ring Rd Westlands", zone: "Westlands", lat: -1.2690, lng: 36.8085, pricePerHour: 120, availableFrom: 6, availableTo: 20, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat"], hasCctv: true, hasRoofing: false, hasGate: true, spotType: "compound", accessInstructions: "Call owner when arriving. Watchman will open gate.", photos: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600"], rating: 4.5, reviewCount: 6, totalBookings: 10, isActive: true },
    { ownerId: 4, title: "Westgate Mall Bypass Spot", description: "Just off the mall access road. Walk 3 minutes to Westgate.", address: "Mwanzi Rd, Westlands", zone: "Westlands", lat: -1.2653, lng: 36.8124, pricePerHour: 180, availableFrom: 8, availableTo: 20, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"], hasCctv: false, hasRoofing: false, hasGate: false, spotType: "driveway", accessInstructions: "Driveway on the left side. No lock needed, just pull in.", photos: ["https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=600"], rating: 4.0, reviewCount: 4, totalBookings: 7, isActive: true },
    // ─── CBD ────────────────────────────────────────────────────
    { ownerId: 4, title: "OTC Plaza Private Driveway", description: "Quiet driveway behind OTC Plaza. Secure and very affordable for CBD.", address: "Mama Ngina St, CBD", zone: "CBD", lat: -1.2874, lng: 36.8216, pricePerHour: 100, availableFrom: 7, availableTo: 18, availableDays: ["Mon","Tue","Wed","Thu","Fri"], hasCctv: false, hasRoofing: false, hasGate: true, spotType: "driveway", accessInstructions: "Black gate with ParkEase sticker. Key in code: 1234.", photos: ["https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=600"], rating: 4.1, reviewCount: 9, totalBookings: 22, isActive: true },
    { ownerId: 5, title: "Kencom Underground Level 3", description: "Deep underground — coolest spot in the CBD! Very secure.", address: "Moi Ave, CBD", zone: "CBD", lat: -1.2865, lng: 36.8229, pricePerHour: 350, availableFrom: 6, availableTo: 22, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat"], hasCctv: true, hasRoofing: true, hasGate: true, spotType: "basement", accessInstructions: "Enter from Moi Ave ramp. Level 3, spot 22. CCTV monitored 24/7.", photos: ["https://images.unsplash.com/photo-1563694983011-6f4d90358083?w=600","https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=600"], rating: 4.8, reviewCount: 15, totalBookings: 30, isActive: true },
    { ownerId: 6, title: "Tom Mboya Street Compound", description: "Large open compound ideal for all-day CBD visits.", address: "Tom Mboya St, CBD", zone: "CBD", lat: -1.2882, lng: 36.8205, pricePerHour: 80, availableFrom: 6, availableTo: 18, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat"], hasCctv: false, hasRoofing: false, hasGate: false, spotType: "compound", accessInstructions: "Just park anywhere marked P1–P5 at the back.", photos: ["https://images.unsplash.com/photo-1573946680645-e4ec9cf76082?w=600"], rating: 3.8, reviewCount: 5, totalBookings: 12, isActive: true },
    { ownerId: 3, title: "St. Andrew's Church Lot", description: "Church allows parking on weekdays. Well maintained and safe.", address: "State House Rd, CBD", zone: "CBD", lat: -1.2860, lng: 36.8200, pricePerHour: 90, availableFrom: 7, availableTo: 17, availableDays: ["Mon","Tue","Wed","Thu","Fri"], hasCctv: true, hasRoofing: false, hasGate: true, spotType: "church", accessInstructions: "Mention ParkEase at the gate. Guard will show you the spot.", photos: ["https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=600"], rating: 4.4, reviewCount: 11, totalBookings: 19, isActive: true },
    { ownerId: 4, title: "Nation Centre Premium Basement", description: "Prestigious address. Air-conditioned basement in Nation Centre tower.", address: "Kimathi St, CBD", zone: "CBD", lat: -1.2850, lng: 36.8230, pricePerHour: 400, availableFrom: 7, availableTo: 20, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat"], hasCctv: true, hasRoofing: true, hasGate: true, spotType: "basement", accessInstructions: "Reception will issue a parking pass. Show your booking ID.", photos: ["https://images.unsplash.com/photo-1563694983011-6f4d90358083?w=600","https://images.unsplash.com/photo-1573946680645-e4ec9cf76082?w=600"], rating: 4.6, reviewCount: 18, totalBookings: 28, isActive: true },
    // ─── UPPERHILL ──────────────────────────────────────────────
    { ownerId: 5, title: "Upperhill Business Park Office", description: "Professional office block with allocated visitor spots. Ideal for business meetings.", address: "Hospital Rd, Upperhill", zone: "Upperhill", lat: -1.2966, lng: 36.8154, pricePerHour: 250, availableFrom: 7, availableTo: 18, availableDays: ["Mon","Tue","Wed","Thu","Fri"], hasCctv: true, hasRoofing: true, hasGate: true, spotType: "office", accessInstructions: "Reception at ground floor will direct you. Show booking ref.", photos: ["https://images.unsplash.com/photo-1563694983011-6f4d90358083?w=600"], rating: 4.7, reviewCount: 14, totalBookings: 25, isActive: true },
    { ownerId: 6, title: "Upperhill Driveway Share", description: "Shaded driveway on residential road. 5 min walk to Upper Hill offices.", address: "Ralph Bunche Rd, Upperhill", zone: "Upperhill", lat: -1.2975, lng: 36.8148, pricePerHour: 130, availableFrom: 7, availableTo: 18, availableDays: ["Mon","Tue","Wed","Thu","Fri"], hasCctv: false, hasRoofing: false, hasGate: false, spotType: "driveway", accessInstructions: "Driveway on the right. Just park and confirm arrival by SMS.", photos: ["https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=600"], rating: 4.3, reviewCount: 7, totalBookings: 11, isActive: true },
    { ownerId: 3, title: "Hill Plaza Visitor Compound", description: "Compound behind Hill Plaza. Great for hospital and office visits.", address: "Ngong Rd, Upperhill", zone: "Upperhill", lat: -1.2959, lng: 36.8162, pricePerHour: 200, availableFrom: 7, availableTo: 20, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat"], hasCctv: true, hasRoofing: false, hasGate: true, spotType: "compound", accessInstructions: "Blue gate. Tell guard you have a ParkEase booking.", photos: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600"], rating: 4.5, reviewCount: 9, totalBookings: 16, isActive: true },
    { ownerId: 4, title: "KNH Medical Centre Open Plot", description: "Open plot next to Kenyatta National Hospital. Very convenient for hospital visitors.", address: "KNH Rd, Upperhill", zone: "Upperhill", lat: -1.2980, lng: 36.8160, pricePerHour: 160, availableFrom: 6, availableTo: 22, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"], hasCctv: false, hasRoofing: false, hasGate: false, spotType: "open_plot", accessInstructions: "Open plot. Park in any marked space.", photos: ["https://images.unsplash.com/photo-1573946680645-e4ec9cf76082?w=600"], rating: 3.9, reviewCount: 6, totalBookings: 9, isActive: true },
    // ─── KILIMANI ───────────────────────────────────────────────
    { ownerId: 6, title: "Kilimani Estate Private Driveway", description: "Quiet residential driveway. Owner is present to assist.", address: "Ngong Rd, Kilimani", zone: "Kilimani", lat: -1.2933, lng: 36.7855, pricePerHour: 110, availableFrom: 7, availableTo: 19, availableDays: ["Mon","Tue","Wed","Thu","Fri"], hasCctv: false, hasRoofing: false, hasGate: true, spotType: "driveway", accessInstructions: "Wooden gate with ParkEase sign. Push to open.", photos: ["https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=600"], rating: 4.2, reviewCount: 5, totalBookings: 8, isActive: true },
    { ownerId: 3, title: "Yaya Centre Overflow Parking", description: "Large open lot right next to Yaya Centre. Great for shoppers.", address: "Argwings Kodhek Rd, Kilimani", zone: "Kilimani", lat: -1.2940, lng: 36.7870, pricePerHour: 170, availableFrom: 8, availableTo: 22, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"], hasCctv: true, hasRoofing: false, hasGate: false, spotType: "open_plot", accessInstructions: "Open lot on the south side of Yaya. Park in any open bay.", photos: ["https://images.unsplash.com/photo-1573946680645-e4ec9cf76082?w=600"], rating: 4.5, reviewCount: 10, totalBookings: 20, isActive: true },
    { ownerId: 4, title: "Argwings Road Gated Compound", description: "Secure compound with 24hr watchman. Electric fence perimeter.", address: "Argwings Kodhek Rd, Kilimani", zone: "Kilimani", lat: -1.2925, lng: 36.7840, pricePerHour: 140, availableFrom: 6, availableTo: 22, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"], hasCctv: true, hasRoofing: false, hasGate: true, spotType: "compound", accessInstructions: "Intercom at gate. Say your name and ParkEase booking number.", photos: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600"], rating: 4.6, reviewCount: 13, totalBookings: 24, isActive: true },
    { ownerId: 5, title: "Kilimani Medical Clinic Lot", description: "Clinic parking available on weekdays. Very organised.", address: "Kirichwa Rd, Kilimani", zone: "Kilimani", lat: -1.2945, lng: 36.7862, pricePerHour: 120, availableFrom: 7, availableTo: 18, availableDays: ["Mon","Tue","Wed","Thu","Fri"], hasCctv: false, hasRoofing: false, hasGate: true, spotType: "church", accessInstructions: "Receptionist at the clinic will note your car plate.", photos: ["https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=600"], rating: 4.0, reviewCount: 4, totalBookings: 6, isActive: true },
    { ownerId: 6, title: "Adams Arcade Adjacent Driveway", description: "Just off Adams Arcade roundabout. Very popular with shoppers.", address: "Ngong Rd, Kilimani", zone: "Kilimani", lat: -1.2950, lng: 36.7848, pricePerHour: 130, availableFrom: 8, availableTo: 21, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"], hasCctv: false, hasRoofing: false, hasGate: false, spotType: "driveway", accessInstructions: "Driveway clearly marked with ParkEase sign. No lock, just park.", photos: ["https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=600"], rating: 4.3, reviewCount: 7, totalBookings: 13, isActive: true },
    // ─── HURLINGHAM ─────────────────────────────────────────────
    { ownerId: 3, title: "Hurlingham Shopping Driveway", description: "Convenient driveway close to Hurlingham Shopping Centre.", address: "Argwings Kodhek Rd, Hurlingham", zone: "Hurlingham", lat: -1.3017, lng: 36.7911, pricePerHour: 100, availableFrom: 7, availableTo: 19, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat"], hasCctv: false, hasRoofing: false, hasGate: false, spotType: "driveway", accessInstructions: "Driveway entrance on left side of main road.", photos: ["https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=600"], rating: 4.1, reviewCount: 6, totalBookings: 10, isActive: true },
    { ownerId: 4, title: "Ralph Bunche Gated Compound", description: "Quiet compound on Ralph Bunche road. Ideal for UN/Embassy staff.", address: "Ralph Bunche Rd, Hurlingham", zone: "Hurlingham", lat: -1.3025, lng: 36.7920, pricePerHour: 120, availableFrom: 7, availableTo: 18, availableDays: ["Mon","Tue","Wed","Thu","Fri"], hasCctv: true, hasRoofing: false, hasGate: true, spotType: "compound", accessInstructions: "Yellow gate. Ring bell, guard will let you in.", photos: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600"], rating: 4.4, reviewCount: 8, totalBookings: 15, isActive: true },
    { ownerId: 5, title: "Hurlingham Private Basement", description: "Basement level under residential apartment block. Very safe and shaded.", address: "Elgon Rd, Hurlingham", zone: "Hurlingham", lat: -1.3010, lng: 36.7905, pricePerHour: 220, availableFrom: 6, availableTo: 22, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"], hasCctv: true, hasRoofing: true, hasGate: true, spotType: "basement", accessInstructions: "Enter via ramp on south side. Spot B-07.", photos: ["https://images.unsplash.com/photo-1563694983011-6f4d90358083?w=600"], rating: 4.7, reviewCount: 11, totalBookings: 19, isActive: true },
    { ownerId: 6, title: "Church of the Nazarene Lot", description: "Church grounds available Mon–Fri. Safe and spacious.", address: "Nairobi West, Hurlingham", zone: "Hurlingham", lat: -1.3030, lng: 36.7918, pricePerHour: 80, availableFrom: 7, availableTo: 17, availableDays: ["Mon","Tue","Wed","Thu","Fri"], hasCctv: false, hasRoofing: false, hasGate: true, spotType: "church", accessInstructions: "Just park in the lot. Caretaker will come around to collect fee.", photos: ["https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=600"], rating: 4.0, reviewCount: 3, totalBookings: 5, isActive: true },
    // ─── PARKLANDS ──────────────────────────────────────────────
    { ownerId: 3, title: "Parklands Office Driveway", description: "Long private driveway with shade from mature trees.", address: "Ojijo Rd, Parklands", zone: "Parklands", lat: -1.2628, lng: 36.8209, pricePerHour: 150, availableFrom: 7, availableTo: 19, availableDays: ["Mon","Tue","Wed","Thu","Fri"], hasCctv: false, hasRoofing: false, hasGate: true, spotType: "driveway", accessInstructions: "Brown gate. Owner will send you PIN via SMS after booking.", photos: ["https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=600"], rating: 4.3, reviewCount: 7, totalBookings: 12, isActive: true },
    { ownerId: 4, title: "Limuru Road Open Compound", description: "Spacious compound on Limuru Road junction. Very easy in and out.", address: "Limuru Rd, Parklands", zone: "Parklands", lat: -1.2618, lng: 36.8219, pricePerHour: 130, availableFrom: 7, availableTo: 20, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat"], hasCctv: false, hasRoofing: false, hasGate: false, spotType: "compound", accessInstructions: "Just pull in. No barrier, self-service.", photos: ["https://images.unsplash.com/photo-1573946680645-e4ec9cf76082?w=600"], rating: 4.1, reviewCount: 5, totalBookings: 8, isActive: true },
    { ownerId: 5, title: "St. Mark's Church Parklands", description: "Church hall carpark available for commuter parking on weekdays.", address: "3rd Parklands Ave, Parklands", zone: "Parklands", lat: -1.2635, lng: 36.8199, pricePerHour: 100, availableFrom: 7, availableTo: 17, availableDays: ["Mon","Tue","Wed","Thu","Fri"], hasCctv: true, hasRoofing: false, hasGate: true, spotType: "church", accessInstructions: "Security at main gate. Show ParkEase booking confirmation.", photos: ["https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=600"], rating: 4.5, reviewCount: 9, totalBookings: 16, isActive: true },
    { ownerId: 6, title: "Parklands Plaza Basement B1", description: "Cool basement level B1 under Parklands Plaza. Premium experience.", address: "Parklands Rd, Parklands", zone: "Parklands", lat: -1.2640, lng: 36.8214, pricePerHour: 280, availableFrom: 7, availableTo: 21, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"], hasCctv: true, hasRoofing: true, hasGate: true, spotType: "basement", accessInstructions: "Main entrance ramp. Ground level reception will assign spot.", photos: ["https://images.unsplash.com/photo-1563694983011-6f4d90358083?w=600","https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600"], rating: 4.6, reviewCount: 12, totalBookings: 22, isActive: true },
    // ─── KAREN ──────────────────────────────────────────────────
    { ownerId: 4, title: "Karen Estate Private Driveway", description: "Beautiful leafy Karen driveway. Very quiet, secure and secluded.", address: "Karen Rd, Karen", zone: "Karen", lat: -1.3320, lng: 36.7125, pricePerHour: 180, availableFrom: 7, availableTo: 20, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat"], hasCctv: true, hasRoofing: false, hasGate: true, spotType: "driveway", accessInstructions: "Grey metal gate. Passcode: K4242.", photos: ["https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=600"], rating: 4.7, reviewCount: 10, totalBookings: 17, isActive: true },
    { ownerId: 3, title: "Karen Shopping Centre Adjacent", description: "Right next to Karen Shopping Centre. Shop and park for less.", address: "Karen Shopping Centre Rd, Karen", zone: "Karen", lat: -1.3330, lng: 36.7135, pricePerHour: 200, availableFrom: 8, availableTo: 21, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"], hasCctv: false, hasRoofing: false, hasGate: false, spotType: "compound", accessInstructions: "Open compound. Park in any bay at the back.", photos: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600"], rating: 4.3, reviewCount: 8, totalBookings: 14, isActive: true },
    { ownerId: 5, title: "Langata Road Gated Compound", description: "On the main Langata Road stretch. Easy access and very secure.", address: "Langata Rd, Karen", zone: "Karen", lat: -1.3310, lng: 36.7118, pricePerHour: 160, availableFrom: 7, availableTo: 19, availableDays: ["Mon","Tue","Wed","Thu","Fri"], hasCctv: true, hasRoofing: false, hasGate: true, spotType: "compound", accessInstructions: "White compound gate. Watchman on duty 24hrs.", photos: ["https://images.unsplash.com/photo-1573946680645-e4ec9cf76082?w=600"], rating: 4.4, reviewCount: 9, totalBookings: 15, isActive: true },
    { ownerId: 6, title: "Karen Church Hall Parking", description: "Large church compound available Mon–Sat. Very spacious.", address: "Karen Hardy Rd, Karen", zone: "Karen", lat: -1.3340, lng: 36.7128, pricePerHour: 120, availableFrom: 7, availableTo: 18, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat"], hasCctv: false, hasRoofing: false, hasGate: true, spotType: "church", accessInstructions: "Mention ParkEase at church gate. Designated spaces at the back.", photos: ["https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=600"], rating: 4.2, reviewCount: 5, totalBookings: 9, isActive: true },
    // ─── LAVINGTON ──────────────────────────────────────────────
    { ownerId: 3, title: "Lavington Mall Adjacent Lot", description: "Open plot next to Lavington Mall. Secure and spacious.", address: "James Gichuru Rd, Lavington", zone: "Lavington", lat: -1.2834, lng: 36.7710, pricePerHour: 150, availableFrom: 7, availableTo: 21, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"], hasCctv: false, hasRoofing: false, hasGate: false, spotType: "open_plot", accessInstructions: "Open lot on the left of the mall entrance. Any bay.", photos: ["https://images.unsplash.com/photo-1573946680645-e4ec9cf76082?w=600"], rating: 4.2, reviewCount: 7, totalBookings: 13, isActive: true },
    { ownerId: 4, title: "James Gichuru Private Driveway", description: "Quiet driveway in leafy Lavington neighbourhood.", address: "James Gichuru Rd, Lavington", zone: "Lavington", lat: -1.2840, lng: 36.7720, pricePerHour: 130, availableFrom: 7, availableTo: 19, availableDays: ["Mon","Tue","Wed","Thu","Fri"], hasCctv: false, hasRoofing: false, hasGate: true, spotType: "driveway", accessInstructions: "White gate with flower pots. Ring bell.", photos: ["https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=600"], rating: 4.4, reviewCount: 6, totalBookings: 10, isActive: true },
    { ownerId: 5, title: "Lavington Estate Compound", description: "Large compound in Lavington estate. Watchman available 24hrs.", address: "Gitanga Rd, Lavington", zone: "Lavington", lat: -1.2828, lng: 36.7715, pricePerHour: 170, availableFrom: 6, availableTo: 22, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"], hasCctv: true, hasRoofing: false, hasGate: true, spotType: "compound", accessInstructions: "Main compound entrance on Gitanga Rd.", photos: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600"], rating: 4.6, reviewCount: 11, totalBookings: 18, isActive: true },
    { ownerId: 6, title: "Dennis Pritt Basement Suite", description: "Exclusive basement in Lavington. Very limited slots available.", address: "Dennis Pritt Rd, Lavington", zone: "Lavington", lat: -1.2845, lng: 36.7730, pricePerHour: 250, availableFrom: 7, availableTo: 20, availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat"], hasCctv: true, hasRoofing: true, hasGate: true, spotType: "basement", accessInstructions: "Ring code: 7890. Level B1, spot 03.", photos: ["https://images.unsplash.com/photo-1563694983011-6f4d90358083?w=600","https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=600"], rating: 4.8, reviewCount: 14, totalBookings: 26, isActive: true },
  ] as any[]).returning();

  console.log(`  Inserted ${insertedSpots.length} spots ✓`);

  const s = (i: number) => insertedSpots[i].id;

  const bookingRows = [
    { spotId: s(2), commuterId: 1, ownerId: 5, date: "2026-01-08", startHour: 8, endHour: 17, totalHours: 9, pricePerHour: 300, surgeMultiplier: 1.0, totalAmount: 2700, platformFee: 405, ownerEarning: 2295, status: "completed", mpesaCode: "QA1234BC" },
    { spotId: s(6), commuterId: 2, ownerId: 5, date: "2026-01-10", startHour: 9, endHour: 17, totalHours: 8, pricePerHour: 350, surgeMultiplier: 1.0, totalAmount: 2800, platformFee: 420, ownerEarning: 2380, status: "completed", mpesaCode: "QB2345CD" },
    { spotId: s(9), commuterId: 1, ownerId: 4, date: "2026-01-15", startHour: 7, endHour: 18, totalHours: 11, pricePerHour: 400, surgeMultiplier: 1.0, totalAmount: 4400, platformFee: 660, ownerEarning: 3740, status: "completed", mpesaCode: "QC3456DE" },
    { spotId: s(0), commuterId: 2, ownerId: 4, date: "2026-02-05", startHour: 8, endHour: 16, totalHours: 8, pricePerHour: 200, surgeMultiplier: 1.0, totalAmount: 1600, platformFee: 240, ownerEarning: 1360, status: "completed", mpesaCode: "QD4567EF" },
    { spotId: s(14), commuterId: 1, ownerId: 6, date: "2026-02-12", startHour: 9, endHour: 17, totalHours: 8, pricePerHour: 110, surgeMultiplier: 1.0, totalAmount: 880, platformFee: 132, ownerEarning: 748, status: "completed", mpesaCode: "QE5678FG" },
    { spotId: s(15), commuterId: 2, ownerId: 3, date: "2026-02-18", startHour: 10, endHour: 18, totalHours: 8, pricePerHour: 170, surgeMultiplier: 1.0, totalAmount: 1360, platformFee: 204, ownerEarning: 1156, status: "completed", mpesaCode: "QF6789GH" },
    { spotId: s(10), commuterId: 6, ownerId: 5, date: "2026-02-20", startHour: 8, endHour: 17, totalHours: 9, pricePerHour: 250, surgeMultiplier: 1.0, totalAmount: 2250, platformFee: 337.5, ownerEarning: 1912.5, status: "completed", mpesaCode: "QG7890HI" },
    { spotId: s(20), commuterId: 3, ownerId: 5, date: "2026-03-03", startHour: 7, endHour: 16, totalHours: 9, pricePerHour: 220, surgeMultiplier: 1.0, totalAmount: 1980, platformFee: 297, ownerEarning: 1683, status: "completed", mpesaCode: "QH8901IJ" },
    { spotId: s(3), commuterId: 1, ownerId: 6, date: "2026-03-06", startHour: 9, endHour: 18, totalHours: 9, pricePerHour: 120, surgeMultiplier: 1.5, totalAmount: 1620, platformFee: 243, ownerEarning: 1377, status: "completed", mpesaCode: "QI9012JK" },
    { spotId: s(27), commuterId: 2, ownerId: 4, date: "2026-03-10", startHour: 8, endHour: 17, totalHours: 9, pricePerHour: 180, surgeMultiplier: 1.0, totalAmount: 1620, platformFee: 243, ownerEarning: 1377, status: "completed", mpesaCode: "QJ0123KL" },
    { spotId: s(22), commuterId: 6, ownerId: 3, date: "2026-03-14", startHour: 9, endHour: 17, totalHours: 8, pricePerHour: 150, surgeMultiplier: 1.0, totalAmount: 1200, platformFee: 180, ownerEarning: 1020, status: "completed", mpesaCode: "QK1234LM" },
    { spotId: s(33), commuterId: 1, ownerId: 5, date: "2026-03-20", startHour: 8, endHour: 17, totalHours: 9, pricePerHour: 170, surgeMultiplier: 1.0, totalAmount: 1530, platformFee: 229.5, ownerEarning: 1300.5, status: "completed", mpesaCode: "QL2345MN" },
    { spotId: s(5), commuterId: 2, ownerId: 4, date: "2026-04-02", startHour: 9, endHour: 17, totalHours: 8, pricePerHour: 100, surgeMultiplier: 1.0, totalAmount: 800, platformFee: 120, ownerEarning: 680, status: "completed", mpesaCode: "QM3456NO" },
    { spotId: s(16), commuterId: 3, ownerId: 4, date: "2026-04-07", startHour: 8, endHour: 18, totalHours: 10, pricePerHour: 140, surgeMultiplier: 1.5, totalAmount: 2100, platformFee: 315, ownerEarning: 1785, status: "completed", mpesaCode: "QN4567OP" },
    { spotId: s(30), commuterId: 6, ownerId: 4, date: "2026-04-10", startHour: 9, endHour: 17, totalHours: 8, pricePerHour: 200, surgeMultiplier: 1.0, totalAmount: 1600, platformFee: 240, ownerEarning: 1360, status: "completed", mpesaCode: "QO5678PQ" },
    { spotId: s(24), commuterId: 1, ownerId: 6, date: "2026-04-15", startHour: 7, endHour: 15, totalHours: 8, pricePerHour: 280, surgeMultiplier: 1.0, totalAmount: 2240, platformFee: 336, ownerEarning: 1904, status: "completed", mpesaCode: "QP6789QR" },
    { spotId: s(8), commuterId: 2, ownerId: 3, date: "2026-04-22", startHour: 8, endHour: 16, totalHours: 8, pricePerHour: 90, surgeMultiplier: 1.0, totalAmount: 720, platformFee: 108, ownerEarning: 612, status: "completed", mpesaCode: "QQ7890RS" },
    { spotId: s(11), commuterId: 6, ownerId: 6, date: "2026-04-25", startHour: 9, endHour: 17, totalHours: 8, pricePerHour: 130, surgeMultiplier: 1.0, totalAmount: 1040, platformFee: 156, ownerEarning: 884, status: "completed", mpesaCode: "QR8901ST" },
    { spotId: s(2), commuterId: 1, ownerId: 5, date: "2026-05-05", startHour: 8, endHour: 17, totalHours: 9, pricePerHour: 300, surgeMultiplier: 1.0, totalAmount: 2700, platformFee: 405, ownerEarning: 2295, status: "confirmed", mpesaCode: "QS9012TU" },
    { spotId: s(9), commuterId: 2, ownerId: 4, date: "2026-05-06", startHour: 9, endHour: 18, totalHours: 9, pricePerHour: 400, surgeMultiplier: 2.0, totalAmount: 7200, platformFee: 1080, ownerEarning: 6120, status: "confirmed", mpesaCode: "QT0123UV" },
    { spotId: s(6), commuterId: 3, ownerId: 5, date: "2026-05-07", startHour: 8, endHour: 16, totalHours: 8, pricePerHour: 350, surgeMultiplier: 1.5, totalAmount: 4200, platformFee: 630, ownerEarning: 3570, status: "confirmed", mpesaCode: "QU1234VW" },
    { spotId: s(15), commuterId: 6, ownerId: 3, date: "2026-05-08", startHour: 9, endHour: 17, totalHours: 8, pricePerHour: 170, surgeMultiplier: 1.0, totalAmount: 1360, platformFee: 204, ownerEarning: 1156, status: "confirmed", mpesaCode: "QV2345WX" },
    { spotId: s(34), commuterId: 1, ownerId: 6, date: "2026-05-09", startHour: 7, endHour: 17, totalHours: 10, pricePerHour: 250, surgeMultiplier: 1.0, totalAmount: 2500, platformFee: 375, ownerEarning: 2125, status: "pending" },
    { spotId: s(20), commuterId: 2, ownerId: 5, date: "2026-05-09", startHour: 8, endHour: 16, totalHours: 8, pricePerHour: 220, surgeMultiplier: 1.0, totalAmount: 1760, platformFee: 264, ownerEarning: 1496, status: "pending" },
    { spotId: s(16), commuterId: 3, ownerId: 4, date: "2026-05-10", startHour: 9, endHour: 18, totalHours: 9, pricePerHour: 140, surgeMultiplier: 1.0, totalAmount: 1260, platformFee: 189, ownerEarning: 1071, status: "pending" },
    { spotId: s(0), commuterId: 6, ownerId: 4, date: "2026-05-10", startHour: 8, endHour: 17, totalHours: 9, pricePerHour: 200, surgeMultiplier: 1.0, totalAmount: 1800, platformFee: 270, ownerEarning: 1530, status: "pending" },
    { spotId: s(27), commuterId: 1, ownerId: 4, date: "2026-05-12", startHour: 8, endHour: 17, totalHours: 9, pricePerHour: 180, surgeMultiplier: 1.0, totalAmount: 1620, platformFee: 243, ownerEarning: 1377, status: "pending" },
    { spotId: s(1), commuterId: 2, ownerId: 3, date: "2026-01-20", startHour: 9, endHour: 17, totalHours: 8, pricePerHour: 150, surgeMultiplier: 1.0, totalAmount: 1200, platformFee: 180, ownerEarning: 1020, status: "cancelled", cancellationReason: "Plans changed" },
    { spotId: s(12), commuterId: 3, ownerId: 3, date: "2026-02-14", startHour: 8, endHour: 16, totalHours: 8, pricePerHour: 200, surgeMultiplier: 1.0, totalAmount: 1600, platformFee: 240, ownerEarning: 1360, status: "cancelled", cancellationReason: "Booked wrong date" },
    { spotId: s(4), commuterId: 1, ownerId: 4, date: "2026-03-28", startHour: 9, endHour: 17, totalHours: 8, pricePerHour: 180, surgeMultiplier: 1.0, totalAmount: 1440, platformFee: 216, ownerEarning: 1224, status: "cancelled", cancellationReason: "Vehicle broke down" },
    { spotId: s(31), commuterId: 6, ownerId: 5, date: "2026-05-15", startHour: 8, endHour: 17, totalHours: 9, pricePerHour: 160, surgeMultiplier: 1.0, totalAmount: 1440, platformFee: 216, ownerEarning: 1224, status: "pending" },
    { spotId: s(24), commuterId: 2, ownerId: 6, date: "2026-05-16", startHour: 9, endHour: 18, totalHours: 9, pricePerHour: 280, surgeMultiplier: 1.0, totalAmount: 2520, platformFee: 378, ownerEarning: 2142, status: "pending" },
    { spotId: s(10), commuterId: 3, ownerId: 5, date: "2026-05-20", startHour: 7, endHour: 16, totalHours: 9, pricePerHour: 250, surgeMultiplier: 1.0, totalAmount: 2250, platformFee: 337.5, ownerEarning: 1912.5, status: "pending" },
  ] as any[];

  const insertedBookings = await db.insert(bookingsTable).values(bookingRows).returning();
  console.log(`  Inserted ${insertedBookings.length} bookings ✓`);

  const completedBookings = insertedBookings.filter(b => b.status === "completed");
  const confirmedBookings = insertedBookings.filter(b => b.status === "confirmed");

  const payoutRows = [...completedBookings, ...confirmedBookings].map(b => ({
    ownerId: b.ownerId,
    bookingId: b.id,
    spotTitle: insertedSpots.find(s => s.id === b.spotId)?.title ?? "",
    grossAmount: b.totalAmount,
    platformFee: b.platformFee,
    netAmount: b.ownerEarning,
    mpesaCode: b.mpesaCode,
    status: b.status === "completed" ? "paid" : "pending",
    periodStart: b.date,
    periodEnd: b.date,
  }));

  await db.insert(payoutsTable).values(payoutRows as any[]);
  console.log(`  Inserted ${payoutRows.length} payouts ✓`);

  const reviewData = [
    { bookingId: insertedBookings[0].id, spotId: s(2), reviewerId: 1, revieweeId: 5, rating: 5, comment: "Excellent spot! Very secure and the access instructions were crystal clear. Will definitely book again.", reviewType: "commuter_to_spot" },
    { bookingId: insertedBookings[1].id, spotId: s(6), reviewerId: 2, revieweeId: 5, rating: 5, comment: "Best parking in CBD. Underground, cool and completely secure. Worth every shilling.", reviewType: "commuter_to_spot" },
    { bookingId: insertedBookings[2].id, spotId: s(9), reviewerId: 1, revieweeId: 4, rating: 4, comment: "Premium spot as advertised. Slightly pricey but the security and convenience is top notch.", reviewType: "commuter_to_spot" },
    { bookingId: insertedBookings[3].id, spotId: s(0), reviewerId: 2, revieweeId: 4, rating: 5, comment: "Grace the owner was very helpful and responsive. The spot was exactly as described.", reviewType: "commuter_to_spot" },
    { bookingId: insertedBookings[4].id, spotId: s(14), reviewerId: 1, revieweeId: 6, rating: 4, comment: "Nice driveway, a bit tight for my SUV but manageable. Good price for Kilimani.", reviewType: "commuter_to_spot" },
    { bookingId: insertedBookings[5].id, spotId: s(15), reviewerId: 2, revieweeId: 3, rating: 5, comment: "Yaya Centre overflow is fantastic! Huge lot, never had trouble finding space. Great value.", reviewType: "commuter_to_spot" },
    { bookingId: insertedBookings[6].id, spotId: s(10), reviewerId: 6, revieweeId: 5, rating: 5, comment: "Professional office parking. Clean, covered and the reception staff were very courteous.", reviewType: "commuter_to_spot" },
    { bookingId: insertedBookings[7].id, spotId: s(20), reviewerId: 3, revieweeId: 5, rating: 5, comment: "Hurlingham basement is a gem. Very safe, CCTV everywhere. My car was safe all day.", reviewType: "commuter_to_spot" },
    { bookingId: insertedBookings[8].id, spotId: s(3), reviewerId: 1, revieweeId: 6, rating: 4, comment: "Good compound, watchman was present and friendly. Gate could do with an upgrade.", reviewType: "commuter_to_spot" },
    { bookingId: insertedBookings[9].id, spotId: s(27), reviewerId: 2, revieweeId: 4, rating: 5, comment: "Karen Estate driveway is exactly the peaceful parking experience I needed. Superb.", reviewType: "commuter_to_spot" },
    { bookingId: insertedBookings[10].id, spotId: s(22), reviewerId: 6, revieweeId: 3, rating: 4, comment: "Parklands driveway is great for office parking. Owner sent the PIN quickly, no delays.", reviewType: "commuter_to_spot" },
    { bookingId: insertedBookings[11].id, spotId: s(33), reviewerId: 1, revieweeId: 5, rating: 5, comment: "Lavington compound is brilliant. Watchman was professional and the compound was clean.", reviewType: "commuter_to_spot" },
    { bookingId: insertedBookings[12].id, spotId: s(5), reviewerId: 2, revieweeId: 4, rating: 4, comment: "Affordable CBD parking. No frills but does the job well. Good for a quick visit.", reviewType: "commuter_to_spot" },
    { bookingId: insertedBookings[13].id, spotId: s(16), reviewerId: 3, revieweeId: 4, rating: 5, comment: "Surge pricing felt high but the location saved me so much time. Worth it for Kilimani.", reviewType: "commuter_to_spot" },
    { bookingId: insertedBookings[14].id, spotId: s(30), reviewerId: 6, revieweeId: 4, rating: 4, comment: "Karen Shopping Centre adjacent is very convenient. Plenty of space, easy to find.", reviewType: "commuter_to_spot" },
    { bookingId: insertedBookings[15].id, spotId: s(24), reviewerId: 1, revieweeId: 6, rating: 5, comment: "Parklands Plaza Basement is superb. Cool, safe and the staff are professional.", reviewType: "commuter_to_spot" },
    { bookingId: insertedBookings[16].id, spotId: s(8), reviewerId: 2, revieweeId: 3, rating: 4, comment: "Church parking was peaceful and very affordable. Ideal if you don't need to stay late.", reviewType: "commuter_to_spot" },
    { bookingId: insertedBookings[17].id, spotId: s(11), reviewerId: 6, revieweeId: 6, rating: 5, comment: "Upperhill driveway is great value. Owner responded instantly to my messages.", reviewType: "commuter_to_spot" },
    { bookingId: insertedBookings[0].id, spotId: s(2), reviewerId: 5, revieweeId: 1, rating: 5, comment: "James was a great guest. Parked neatly and left on time. Highly recommended commuter.", reviewType: "owner_to_commuter" },
    { bookingId: insertedBookings[6].id, spotId: s(10), reviewerId: 5, revieweeId: 6, rating: 5, comment: "Amina was a perfect guest. Very punctual and kept the spot clean.", reviewType: "owner_to_commuter" },
    { bookingId: insertedBookings[9].id, spotId: s(27), reviewerId: 4, revieweeId: 2, rating: 4, comment: "Grace is a reliable commuter. Always pays promptly via Mpesa. Happy to host again.", reviewType: "owner_to_commuter" },
    { bookingId: insertedBookings[11].id, spotId: s(33), reviewerId: 5, revieweeId: 1, rating: 5, comment: "James is a great guest — the spot was spotless when he left. 5 stars!", reviewType: "owner_to_commuter" },
  ] as any[];

  await db.insert(reviewsTable).values(reviewData);
  console.log(`  Inserted ${reviewData.length} reviews ✓`);

  console.log(`\n✅ Seeding complete!`);
  console.log(`   35 spots | ${bookingRows.length} bookings | ${reviewData.length} reviews | ${payoutRows.length} payouts`);

  process.exit(0);
}

seed().catch(err => {
  console.error("Seed failed:", err);
  process.exit(1);
});
